FROM node:14

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el código fuente del proyecto
COPY . .

EXPOSE 8080

CMD ["node", "app.js"]
